# 上下文初始化加载
info:
  name: server-c
  contact: c服务
spring:
  application:
    name: server-c
server:
  port: 6061
  servlet:
    context-path: /server-c

eureka:
  #作为客户端(相当于一个普通服务端),用于注册到注册中心的客户端
  client:
    # 是否注册到eurekaserver
    registerWithEureka: true
    # 是否拉注册取信息
    fetchRegistry: true
    # eureka server地址
    serviceUrl:
      # 指定连接到的注册中心
      defaultZone: http://127.0.0.1:8761/eureka/

  #当前服务实例信息(这里相于看作一个普通服务)
  instance:
    #实例心跳时间(默认30s)
    lease-renewal-interval-in-seconds: 30
    #超过上次心跳30s 认为宕机(默认90s)
    lease-expiration-duration-in-seconds: 30
    prefer-ip-address: true
