# 上下文初始化加载
info:
  name: Eureka server
  contact: 注册中心
spring:
  application:
    name: eureka-server
server:
  port: 8761

eureka:
  #作为客户端(相当于一个普通服务端),用于注册到注册中心的客户端
  client:
    # 是否注册到eurekaserver
    registerWithEureka: true
    # 是否拉注册取信息
    fetchRegistry: true
    # eureka server地址
    serviceUrl:
      # 指定连接到的注册中心
      defaultZone: http://127.0.0.1:8761/eureka/

  #这里的服务指的是作为注册中心服务，用于接收其它普通服务注册进来的
  #上面的client 就是用于作为一个普通服务连接注册中的客户端
  server:
    waitTimeInMsWhenSyncEmpty: 0
    # false 关闭自我保护，不管如何都要剔除心跳检测异常的服务
    enableSelfPreservation: false
    #服务踢除时间(默认60000ms)
    eviction-interval-timer-in-ms: 60000
    #eureka 集群刷新间隔
    peer-eureka-nodes-update-interval-ms: 10000

  #当前服务实例信息(这里相于看作一个普通服务)
  instance:
    #实例心跳时间(默认30s)
    lease-renewal-interval-in-seconds: 30
    #超过上次心跳30s 认为宕机(默认90s)
    lease-expiration-duration-in-seconds: 30
    prefer-ip-address: true
